name: Node CI

on:
  push:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: make install

      - name: Hexlet project check
        run: make lint
